
  server {
   server_name novy.daktoinc.co.uk;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

 ssl_certificate /etc/cloudflare/pem;
ssl_certificate_key /etc/cloudflare/key;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

 location / {
      return 301 $scheme://novyhome.daktoinc.co.uk$request_uri; 
   }

}

