    server {
 	 server_name  localhost;

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/cloudflare/pem;
        ssl_certificate_key /etc/cloudflare/key;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;


	location / {
		    default_type text/html;
	return 418 "<html><head><title>418 I'm a teapot :3</title></head><body><center><h1>418 I'm a teapot :3</h1></center><hr><center>Nginx/1.28.0 (Arch) Server at daktoinc.co.uk Port 443</center></body></html>";
	}
    }



