
  server {
   server_name novymap-qvh.top;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

 ssl_certificate /etc/letsencrypt/live/novymap-qvh.top/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/novymap-qvh.top/privkey.pem;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

 location / {
      return 301 $scheme://www.novymap-qvh.top$request_uri; 
   }

}

