server {

 	 server_name map.novymap-qvh.top;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

	ssl_certificate	/etc/letsencrypt/live/novymap-qvh.top/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/novymap-qvh.top/privkey.pem;

        #charset koi8-r;
        #access_log  logs/host.access.log  main;

 error_page  404 500 502 503 504  /50x.html;

	    root   /etc/novy/map;

 	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }

	location / {
		 add_header Cache-Control "no-cache";
	    index  index.html;
	}

	location /novydontpro {
		return 301 ..;
	}

	location /creative {
		return 301 ..;
	}

      	
	location /standalone {
		proxy_pass http://localhost:6081/smp/standalone;
        }

	location /crstandalone {

		proxy_pass http://localhost:6081/creative/standalone;
        }

	location /hack/faces/body/ {
            proxy_pass http://localhost:6081/shizuku/full/128/;
	   
        }

location /hack/faces/16x16/ {
            proxy_pass http://localhost:6081/shizuku/front/128/;
	    
        }

        location = /hack/_markers_/marker_world.json
        {
            return 301 '/novy.php';
        }
 location = /novy.php
        {
            return 301 '/api/internal/novy.php';
        }

        location = /api/internal/novy.php {
            return 301 '/api/internal/novy';
        }
        location = /api/internal/novy {
            include fastcgi.conf;
	    fastcgi_param  SCRIPT_FILENAME    $document_root/api/internal/novy.php;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }

     location = /api/internal/shot.php {
	    return 301 'https://api.novymap-qvh.top/api/shot.php';
	          } 
 
        location /hack/_markers_ {
		  add_header 'Access-Control-Allow-Origin' '*';
		alias /etc/novy/map/markers;
        }
	
	location /qvhconfig.json  {
	    root   /etc/novy/map;
        }

	location /crqvhconfig.json  {
	    root   /etc/novy/map;
        }

     
    }


server {


        listen 9000;
	
	location / {
		proxy_pass https://minecraft.novylen.net/map/;
        }

	location /shizuku/ {
   proxy_pass https://vzge.me/;
	    proxy_set_header User-Agent 'novymap-qvh/rolling (+https://novymap-qvh.top/; <exkc@exkc.moe>)';
	    proxy_set_header Host vzge.me;

	}

}
