    server {
	         listen       4000;
        server_name  localhost;
	    root   /etc/novy/admin;
	    index index.php;
	 location  / {
		 try_files $uri $uri.php$is_args$query_string;
        }
location /admin_lines/ {
            include fastcgi.conf;
 fastcgi_split_path_info       ^(.+admin_lines)(.*)$;
     fastcgi_param PATH_INFO       $fastcgi_path_info;
     fastcgi_param SCRIPT_FILENAME '/etc/novy/admin/admin_lines.php';
 client_max_body_size 100M;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;

}
	location ~ .(php)$ {
 client_max_body_size 100M;
            include fastcgi.conf;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }
		
	   location  ~ .(phphidden)$ {
		   return 404;
        }

        error_page 404  500 502 503 504  /50x.html;
	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }
    }



      server {
 	 server_name  admin.novymap-qvh.top;
        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

	ssl_certificate	/etc/letsencrypt/live/novymap-qvh.top/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/novymap-qvh.top/privkey.pem;


 error_page   500 502 503 504  /50x.html;
	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }

	location /img/novymap-qvh.png {
		alias /etc/novy/shared/novymap-qvh.png;
	}

	location / {
       proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host "admin.novymap-qvh.top";
	proxy_redirect http://admin.novymap-qvh.top:4000/ https://$host:443/;
	    sub_filter 'with &amp;HACK' '';
	    sub_filter 'bulma.min.css">' 'bulma.min.css"><link rel="icon" type="image/png" href="/img/novymap-qvh.png">';
 client_max_body_size 100M;
		proxy_pass http://127.0.0.1:4180;
        }



    }



