    server {
	         listen       4000;
        server_name  localhost;
	    root   /etc/novy/admin;
	    index index.php;
	 location  / {
		 try_files $uri $uri.php$is_args$query_string;
        }
location /admin_lines/ {
            include fastcgi.conf;
 fastcgi_split_path_info       ^(.+admin_lines)(.*)$;
     fastcgi_param PATH_INFO       $fastcgi_path_info;
     fastcgi_param SCRIPT_FILENAME '/etc/novy/admin/admin_lines.php';
 client_max_body_size 100M;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;

}
	location ~ .(php)$ {
 client_max_body_size 100M;
            include fastcgi.conf;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }
		
	   location  ~ .(phphidden)$ {
		   return 404;
        }

        error_page 404  500 502 503 504  /50x.html;
	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }
    }



