server {

 	 server_name novymap.daktoinc.co.uk;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

	ssl_certificate	/etc/cloudflare/pem;
ssl_certificate_key /etc/cloudflare/key;

        #charset koi8-r;
        #access_log  logs/host.access.log  main;

 error_page  404 500 502 503 504  /50x.html;
		 add_header Cache-Control "no-cache";

	    root   /etc/novy/map;

 	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }

	location / {
	    index  index.html;
	    try_files $uri $uri/ /index.html;
	}

	location /novydontpro {
		return 301 ..;
	}

	location /creative {
		return 301 ..;
	}

	location ~ ^/api/ {
            return 404;
        }

	# smp 
	location /mapdata/smp/standalone {
		proxy_pass http://localhost:6081/smp/standalone;
        }

	location /mapdata/smp/hijack/marker/faces/body/ {
            proxy_pass http://localhost:6081/shizuku/frontfull/128/;
	   
        }

    location /mapdata/smp/hijack/marker/_markers_ {
		alias /etc/novy/map/markers;
        }


location /mapdata/smp/hijack/marker/faces/16x16/ {
            proxy_pass http://localhost:6081/shizuku/front/128/;
	    
        }

        location = /mapdata/smp/hijack/marker/_markers_/marker_world.json
        {
 include fastcgi.conf;
	    fastcgi_param  SCRIPT_FILENAME    $document_root/api/internal/novy.php;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;

        }

 location = /mapdata/smp/hijack/config {
            include fastcgi.conf;
	    fastcgi_param  SCRIPT_FILENAME    $document_root/api/internal/confighijacker.php;
	    fastcgi_param  MCSERVER  smp;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }

	location /mapdata/smp/hijack/marker/ {
            proxy_pass 'http://localhost:6081/smp/standalone/MySQL_markers.php?marker=';
	   
        }


	location /mapdata/smp/images/blank.png {
	return 301 'https://novymap.daktoinc.co.uk/images/blank.png';
			}

	# cmp
	
	location = /mapdata/cmp/hijack/config {
            include fastcgi.conf;
	    fastcgi_param  SCRIPT_FILENAME    $document_root/api/internal/confighijacker.php;
	    fastcgi_param  MCSERVER  cmp;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }

	location /mapdata/cmp/standalone {

		proxy_pass http://localhost:6081/creative/standalone;
        }

location /mapdata/cmp/hijack/marker/faces/16x16/ {
            proxy_pass http://localhost:6081/shizuku/front/128/;
	    
        }

	location /mapdata/cmp/hijack/marker/faces/body/ {
            proxy_pass http://localhost:6081/shizuku/frontfull/128/;
	   
        }

	location /mapdata/cmp/hijack/marker/ {
            proxy_pass 'http://localhost:6081/creative/standalone/MySQL_markers.php?marker=';
	   
        }

	location /mapdata/cmp/images/blank.png {
	return 301 'https://novymap.daktoinc.co.uk/images/blank.png';
	}
     
  
     
    }


server {


        listen 9000;
	
	location / {
		proxy_pass https://minecraft.novylen.net/map/;
        }

	location /shizuku/ {
   proxy_pass https://vzge.me/;
	    proxy_set_header User-Agent 'novymap-qvh/rolling (+https://novymap-qvh.top/; <exkc@exkc.moe>)';
	    proxy_set_header Host vzge.me;

	}

}
