   server {
 	 server_name  novyhome.daktoinc.co.uk;
        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000';

	ssl_certificate	/etc/cloudflare/pem;
ssl_certificate_key /etc/cloudflare/key;

        #access_log  logs/host.access.log  main;

	 location /shared/ {
		 root /etc/novy;
	 }

	 location  / {
	    root   /etc/novy/home;
	    index  index.php;
        }

	   location  ~ .(php)$ {
	   root   /etc/novy/home;
            include fastcgi.conf;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }

 error_page 404  500 502 503 504  /50x.html;
	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }

	  
 
    }



