    server {
 	 server_name  novyauth.novymap-qvh.top;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 
        #charset koi8-r;

	ssl_certificate	/etc/cloudflare/pem;
ssl_certificate_key /etc/cloudflare/key;


        #access_log  logs/host.access.log  main;



	location / {
            include fastcgi.conf;
            fastcgi_pass unix:/var/lib/forgejo/QwQ;
        }
		
 
    }



