        server {
 	 server_name  novyapi.daktoinc.co.uk;
        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
 add_header Alt-Svc 'h3=:443; ma=864000'; 

	ssl_certificate	/etc/cloudflare/pem;
ssl_certificate_key /etc/cloudflare/key;

	    root   /etc/novy/api;

	    location /shared/ {
		    root /etc/novy;
	    }

 location  / {
	  index index.php;
		 try_files $uri $uri.php$is_args$query_string;
        }
location /api/ {
            include fastcgi.conf;
 fastcgi_split_path_info       ^(.+api)(.*)$;
     fastcgi_param PATH_INFO       $fastcgi_path_info;
     fastcgi_param SCRIPT_FILENAME '/etc/novy/api/api/api.php';
 client_max_body_size 100M;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
	    add_header Access-Control-Allow-Origin "https://novymap.daktoinc.co.uk";
	    add_header Access-Control-Allow-Origin "GET, OPTIONS";

}

	   location  ~ .(php)$ {
            include fastcgi.conf;
            fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        }
 error_page 404  500 502 503 504  /50x.html;
	location = /50x.html {
            alias /etc/novy/shared/50x.html;
        }

 
    }



