    server {
 	 server_name  localhost;

        listen 443 ssl;
        listen [::]:443 ssl; 
 listen 443 quic; 
  listen [::]:443 quic; 
 add_header Alt-Svc 'h3=:443; ma=864000' ; 
        #charset koi8-r;

 ssl_certificate	/etc/letsencrypt/live/novymap-qvh.top/fullchain.pem;
 ssl_certificate_key /etc/letsencrypt/live/novymap-qvh.top/privkey.pem;

        #access_log  logs/host.access.log  main;


	location / {
		    default_type text/html;
	return 418 "<html><head><title>418 I'm a teapot :3</title></head><body><center><h1>418 I'm a teapot :3</h1></center><hr><center>Random  Server :3</center></body></html>";
	}
    }



